### ISSUE TITLE
How can I pull-request JUnit 5 documentation?

### ISSUE THREAD

**Issue by volkovs** [junit-team/junit-team.github.io#1]
I didn't find the way to fix a bug in [JUnit 5 user guide](http://junit.org/junit5/docs/snapshot/user-guide/#writing-tests-dependency-injection):

It uses `@InjectMock` annotation:

>     @Test
>     void simpleTestWithInjectedMock(@InjectMock Person person) {
>         assertEquals("Dilbert", person.getName());
>     }

But [Mockito parameter resolver](https://github.com/junit-team/junit5-samples/blob/master/junit5-mockito-extension/src/main/java/com/example/mockito/MockitoExtension.java) checks for regular `@Mock`.

**Comment by marcphilipp** [comment]
Good catch!

The sources of the user guide are located in the [documentation module](https://github.com/junit-team/junit5/tree/master/documentation/src/docs/asciidoc) of the junit5 repo.

I've created an issue over there to track it: junit-team/junit5#376.
